pool:
  name: MynewAgentPool

variables:
  BuildConfiguration: "release"
  BuildPlatform: "any cpu"

stages:
  - stage:
    displayName: Build
    jobs:
      - job:
        displayName: Build_And_Publish
        steps:
          - task: NuGetCommand@2
            inputs:
              command: 'restore'
              restoreSolution: '**/*.sln'
              feedsToUse: 'select'
              vstsFeed: '0ea46223-8f6c-411f-a59c-507a08b8ab35'
          - task: VSBuild@1
            inputs:
              solution: '**\*.sln'
          - task: PublishBuildArtifacts@1
            displayName: Publish_Artifact
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  - stage: 
    displayName: Infrastructure_Provisioning
    jobs:
      - job:
        displayName: Terrafrom
        steps:
           - task: TerraformTaskV3@3
             inputs:
               provider: 'azurerm'
               command: 'init'
               workingDirectory: '$(System.DefaultWorkingDirectory)\gitclones\clones\PartsUnlimitedE2E\automation\terraform1'
               backendServiceArm: 'Free Trial(2f5a2cf9-f99c-4c7f-97d9-c72841dd07b6)'
               backendAzureRmResourceGroupName: 'sa-tf-backends'
               backendAzureRmStorageAccountName: 'azb23tfremotebackends1'
               backendAzureRmContainerName: 'tfremotebackends1'
               backendAzureRmKey: 'dev.terraform.tfstate'
               environmentServiceNameAzureRM: 'Free Trial(2f5a2cf9-f99c-4c7f-97d9-c72841dd07b6)'
           - task: TerraformTaskV3@3
             inputs:
               provider: 'azurerm'
               command: 'plan'
               workingDirectory: '$(System.DefaultWorkingDirectory)\gitclones\clones\PartsUnlimitedE2E\automation\terraform1'
               environmentServiceNameAzureRM: 'Free Trial(2f5a2cf9-f99c-4c7f-97d9-c72841dd07b6)'
           - task: TerraformTaskV3@3
             inputs:
               provider: 'azurerm'
               command: 'apply'
               workingDirectory: '$(System.DefaultWorkingDirectory)\gitclones\clones\PartsUnlimitedE2E\automation\terraform1'
               environmentServiceNameAzureRM: 'Free Trial(2f5a2cf9-f99c-4c7f-97d9-c72841dd07b6)'